apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-ui-ingress
  namespace: gym
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - wgodoi.ddns.net
      secretName: gym-ui-tls
  rules:
    - host: wgodoi.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gym-ui-service
                port:
                  number: 80
